# Generated by Django 3.2.11 on 2022-02-15 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='color',
            field=models.CharField(default='#000', help_text='icon color', max_length=20),
        ),
    ]
