exclude: "^docs/|/migrations/"
default_stages: [commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black
        args: [--line-length=120]
        exclude: >
          (?x)^(
                 .github/
             )$

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args: ["--config=setup.cfg", "--max-line-length=120"]
        additional_dependencies: [flake8-isort]

  # Custom hook - Comment out html livejs script - (uses "django comment" to comment out script tag)
  # https://stackoverflow.com/questions/59499061/how-to-run-custom-shell-script-file-before-pre-commit-hook
  - repo: local
    hooks:
      - id: livejs-comment
        name: livejs-comment
        entry: bash -c "find . -path '*base.html' | xargs sudo sed -ri 's/^(\s*)(<script.*livejs.*script>)/\1\{\# \2 \#\}/' "
        language: system
        types: [html]
        pass_filenames: false

# sets up .pre-commit-ci.yaml to ensure pre-commit dependencies stay up to date
ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false
